import { ArrowRight } from "lucide-react";

const AIMeditation = () => {
  return (
    <section className="section section-dark the-ai-meditation" data-theme="dark">
      <div className="hfh-container">
        <header className="ts-header">
          <span className="row-label gold">THE AI MEDITATION</span>
          <h2 className="section-header light">A Meditation That Adapts To You.</h2>
          <p className="section-sub light">Speak. Redirect. Layer. The first AI meditation you can actually steer in real time.</p>
        </header>

        <div className="reveal-row reverse">
          <div className="reveal-visual tier-2-visual mirrored">
            <div className="ambient-halo halo-soft"></div>
            <div className="ambient-ribbon ribbon-gold"></div>
            <img
              src="https://www.genspark.ai/api/files/s/C0hsxh35"
              alt="AI Meditation app interface on a phone showing pulsing meditation orb, voice redirect microphone, and frequency overlay"
              loading="lazy"
            />
            <span className="floating-pill pill-purple">CALM</span>
            <span className="floating-pill pill-gold">FLOW</span>
          </div>
          <div className="reveal-copy light">
            <h3>Personalized in real time. Generated by AI. Anchored by frequency.</h3>
            <p>Generate a meditation about anything. Anxiety before a meeting. Recovery after a workout. Grief. Confidence. Sleep. The AI builds it on the spot.</p>
            <p>Don't like where it's going? Talk to it. Redirect it mid-session. Overlay any frequency on top. Meditation that adapts to you, not a 10-minute recording someone made in a studio three years ago.</p>
            <a href="#order" className="btn btn-gold">
              Try the AI Meditation <ArrowRight size={18} />
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIMeditation;
